import { DishInterface } from '@/types/dish';

export const foodAndDrinks: DishInterface[] = [
  {
    idDish: '0',
    idCate: '0',
    name: 'Cà phê đen',
    quantity: 100,
    price: '12000',
    thumbnail: '/images/milk-coffee.webp',
  },
  {
    idDish: '1',
    idCate: '0',
    name: 'Cà phê sữa',
    quantity: 100,
    price: '15000',
    thumbnail: '/images/milk-coffee.webp',
  },
  {
    idDish: '2',
    idCate: '0',
    name: 'Bạc xỉu',
    quantity: 100,
    price: '18000',
    thumbnail: '/images/milk-coffee.webp',
  },
  {
    idDish: '3',
    idCate: '1',
    name: 'Cam ép',
    quantity: 100,
    price: '15000',
    thumbnail: '/images/milk-coffee.webp',
  },
  {
    idDish: '4',
    idCate: '4',
    name: 'Hamberger thịt bò nướng',
    quantity: 100,
    price: '20000',
    thumbnail: '/images/milk-coffee.webp',
  },
  {
    idDish: '5',
    idCate: '4',
    name: 'Hamberger thịt bò nướng lá lốt',
    quantity: 100,
    price: '25000',
    thumbnail: '/images/milk-coffee.webp',
  },
  {
    idDish: '6',
    idCate: '3',
    name: 'Bánh mì bò lá lốt',
    quantity: 100,
    price: '25000',
    thumbnail: '/images/milk-coffee.webp',
  },
  {
    idDish: '7',
    idCate: '3',
    name: 'Bánh mì ốp la',
    quantity: 100,
    price: '15000',
    thumbnail: '/images/milk-coffee.webp',
  },
  {
    idDish: '8',
    idCate: '3',
    name: 'Bánh mì thập cẩm',
    quantity: 100,
    price: '25000',
    thumbnail: '/images/milk-coffee.webp',
  },
];
